cmake_minimum_required(VERSION 3.25)
project(ProjectMC VERSION 0.0.1 LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
option(PROJECTMC_BUILD_GAME "Build game client" ON)
option(PROJECTMC_BUILD_SERVER "Build dedicated server" ON)
add_subdirectory(shared)
if(PROJECTMC_BUILD_GAME)
  add_subdirectory(game)
endif()
if(PROJECTMC_BUILD_SERVER)
  add_subdirectory(server)
endif()
